version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: UTC
    open-pull-requests-limit: 10
    reviewers:
      - alex-rn
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: UTC
    open-pull-requests-limit: 5
    reviewers:
      - alex-rn
    groups:
      github-actions:
        patterns:
          - "*"
