import {
  ASSETS_CONFIG,
  COMPATIBILITY_DATE,
  COMPATIBILITY_FLAGS,
  RATE_LIMIT_BINDINGS,
} from './constants.mjs';
import {
  isReservedProductionRateLimitId,
  isReservedProductionResourceId,
  validateAppDomain,
  validateResourceId,
} from './validate.mjs';

function ownRateLimitId(offset) {
  let n = offset;
  for (let i = 0; i < 900000; i += 1) {
    const id = String(100000 + (n % 900000));
    if (!isReservedProductionRateLimitId(id)) return id;
    n += 1;
  }
  throw new Error('Could not allocate a non-reserved rate-limit namespace id.');
}

/**
 * Stable per-worker Rate Limiting namespace ids (not secrets).
 * Re-runs with the same worker name keep the same ids.
 * @param {string} workerName
 * @returns {string[]}
 */
export function rateLimitNamespaceIds(workerName) {
  const ids = [];
  for (let i = 0; i < RATE_LIMIT_BINDINGS.length; i += 1) {
    let hash = 2166136261;
    const input = `${workerName}:${RATE_LIMIT_BINDINGS[i].name}`;
    for (let c = 0; c < input.length; c += 1) {
      hash ^= input.charCodeAt(c);
      hash = Math.imul(hash, 16777619);
    }
    const unsigned = hash >>> 0;
    ids.push(ownRateLimitId(unsigned % 900000));
  }
  const unique = new Set(ids);
  let bump = 1;
  while (unique.size < ids.length) {
    for (let i = 0; i < ids.length; i += 1) {
      if (ids.filter((id) => id === ids[i]).length > 1) {
        ids[i] = ownRateLimitId((Number(ids[i]) + bump) % 900000);
      }
    }
    unique.clear();
    ids.forEach((id) => unique.add(id));
    bump += 1;
  }
  return ids;
}

export function assertOwnResourceIds(ids) {
  for (const id of ids) {
    const check = validateResourceId(id, 'Binding id');
    if (!check.ok) throw new Error(check.error);
  }
}

/**
 * @param {{
 *   name: string,
 *   hostnameMode: 'workers-dev' | 'custom',
 *   hostname?: string | null,
 *   appDomain: string,
 *   d1: { name: string, id: string },
 *   kv: { name?: string, id: string },
 * }} input
 */
export function buildLocalWranglerConfig(input) {
  assertOwnResourceIds([input.d1.id, input.kv.id]);
  if (isReservedProductionResourceId(input.d1.id) || isReservedProductionResourceId(input.kv.id)) {
    throw new Error('Refusing to emit reserved production binding ids.');
  }
  const domainCheck = validateAppDomain(input.appDomain);
  if (!domainCheck.ok) throw new Error(domainCheck.error);

  const rateIds = rateLimitNamespaceIds(input.name);
  if (rateIds.some((id) => isReservedProductionRateLimitId(id))) {
    throw new Error('Refusing to emit reserved production rate-limit namespace ids.');
  }
  const config = {
    $schema: 'node_modules/wrangler/config-schema.json',
    name: input.name,
    main: 'src/worker/index.ts',
    compatibility_date: COMPATIBILITY_DATE,
    compatibility_flags: [...COMPATIBILITY_FLAGS],
    workers_dev: true,
    preview_urls: false,
    assets: { ...ASSETS_CONFIG, run_worker_first: [...ASSETS_CONFIG.run_worker_first] },
    kv_namespaces: [
      { binding: 'KV', id: input.kv.id },
      { binding: 'OAUTH_KV', id: input.kv.id },
    ],
    d1_databases: [
      {
        binding: 'DB',
        database_name: input.d1.name,
        database_id: input.d1.id,
      },
    ],
    vars: {
      APP_DOMAIN: input.appDomain,
    },
    ratelimits: RATE_LIMIT_BINDINGS.map((binding, index) => ({
      name: binding.name,
      namespace_id: rateIds[index],
      simple: { limit: binding.limit, period: binding.period },
    })),
  };

  if (input.hostnameMode === 'custom' && input.hostname) {
    config.routes = [{ pattern: input.hostname, custom_domain: true }];
  }

  return config;
}

export function serializeWranglerJsonc(config) {
  const body = JSON.stringify(config, null, 2);
  return [
    '// Generated by `npm run setup`. Do not commit.',
    '// This file binds YOUR Cloudflare D1/KV resources. It is not the committed production wrangler.jsonc.',
    body,
    '',
  ].join('\n');
}

export function stripJsonc(text) {
  return String(text)
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^\s*\/\/.*$/gm, '');
}

export function parseLocalWranglerConfig(text) {
  const parsed = JSON.parse(stripJsonc(text));
  const d1 = parsed.d1_databases?.[0] ?? {};
  const kv = parsed.kv_namespaces?.[0] ?? {};
  return {
    name: parsed.name ?? null,
    appDomain: parsed.vars?.APP_DOMAIN ?? null,
    hostname: parsed.routes?.[0]?.pattern ?? null,
    hostnameMode: parsed.routes?.[0]?.custom_domain ? 'custom' : 'workers-dev',
    d1: {
      name: d1.database_name ?? null,
      id: d1.database_id ?? null,
    },
    kv: {
      id: kv.id ?? null,
    },
    raw: parsed,
  };
}

export function workersDevOrigin(workerName, accountSubdomain) {
  if (!accountSubdomain) {
    return `https://${workerName}.<your-subdomain>.workers.dev`;
  }
  return `https://${workerName}.${accountSubdomain}.workers.dev`;
}

export function originFromHostname(hostname) {
  if (!hostname) return null;
  if (hostname.startsWith('http://') || hostname.startsWith('https://')) return hostname.replace(/\/$/, '');
  return `https://${hostname}`;
}
