-- Stranger-safe product showcase for `npm run setup -- --seed-demo`.
-- Fake English household only. Applied when the instance is still empty.
-- D1 remote rejects a multi-arm compound SELECT ("too many terms"),
-- so each row is its own INSERT…SELECT.
-- Generated by scripts/lib/cloudflare-setup/seed-demo-sql.mjs — edit that
-- module and regenerate this file; do not use compound SELECT arms.
-- Pulse Warnings coverage: Everyday Card already negative (household
-- total stays positive); Travel Cash reaches zero soon; Sterling Current
-- (and UK/GBP) go negative later. City rent is recurring only.

INSERT INTO settings (key, value)
SELECT 'setup_demo_seed', '1'
WHERE NOT EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed')
  AND (SELECT COUNT(*) FROM accounts) = 0
  AND (SELECT COUNT(*) FROM operations) = 0;

INSERT INTO fx_rates (code, rate_e9, updated_at)
SELECT 'EUR', 1080000000, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM fx_rates WHERE code = 'EUR');

INSERT INTO fx_rates (code, rate_e9, updated_at)
SELECT 'GBP', 1270000000, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM fx_rates WHERE code = 'GBP');

INSERT INTO fx_rates (code, rate_e9, updated_at)
SELECT 'CAD', 740000000, strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM fx_rates WHERE code = 'CAD');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Everyday Checking',
  'Example Bank',
  'Checking',
  'Household',
  'USA',
  'USD',
  428000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  0
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts);

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Emergency Savings',
  'Example Bank',
  'Savings',
  'Household',
  'USA',
  'USD',
  1250000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  1
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Emergency Savings' AND owner = 'Household');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Everyday Card',
  'Example Bank',
  'Credit',
  'Household',
  'USA',
  'USD',
  -64000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  2
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Everyday Card' AND owner = 'Household');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Travel Cash',
  NULL,
  'Cash',
  'Household',
  'USA',
  'EUR',
  21500,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  3
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Travel Cash' AND owner = 'Household');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Rhine Checking',
  'Rhine Bank',
  'Checking',
  'Household',
  'Germany',
  'EUR',
  318000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  4
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Rhine Checking' AND owner = 'Household');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Sterling Current',
  'Thames Bank',
  'Checking',
  'Household',
  'United Kingdom',
  'GBP',
  154000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  5
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Sterling Current' AND owner = 'Household');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Maple Everyday',
  'Maple Credit Union',
  'Checking',
  'Household',
  'Canada',
  'CAD',
  184000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  6
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Maple Everyday' AND owner = 'Household');

INSERT INTO accounts (
  name, bank, type, owner, country, currency, balance_minor, balance_updated_at, sort
)
SELECT
  'Maple Savings',
  'Maple Credit Union',
  'Savings',
  'Household',
  'Canada',
  'CAD',
  620000,
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
  7
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM accounts WHERE name = 'Maple Savings' AND owner = 'Household');

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-90 days'),
  a.id,
  'income',
  'Acme Studio',
  'Monthly salary',
  'Income',
  'Salary',
  320000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (SELECT 1 FROM operations);

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-60 days'),
  a.id,
  'income',
  'Acme Studio',
  'Monthly salary',
  'Income',
  'Salary',
  320000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly salary'
      AND date = date('now', '-60 days')
      AND store = 'Acme Studio'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-30 days'),
  a.id,
  'income',
  'Acme Studio',
  'Monthly salary',
  'Income',
  'Salary',
  320000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly salary'
      AND date = date('now', '-30 days')
      AND store = 'Acme Studio'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-84 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8480,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-84 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-77 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -7280,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-77 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-70 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -7840,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-70 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-63 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8600,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-63 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-56 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -7400,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-56 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-49 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8160,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-49 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-42 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8720,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-42 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-35 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -7520,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-35 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-28 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8280,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-28 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-21 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8840,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-21 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-14 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -7840,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-14 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-7 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Weekly groceries',
  'Food',
  'Groceries',
  -8400,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-7 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-82 days'),
  a.id,
  'expense',
  'Harbor Cafe',
  'Morning coffee',
  'Dining',
  NULL,
  -650,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Morning coffee'
      AND date = date('now', '-82 days')
      AND store = 'Harbor Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-68 days'),
  a.id,
  'expense',
  'Harbor Cafe',
  'Lunch special',
  'Dining',
  NULL,
  -1850,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Lunch special'
      AND date = date('now', '-68 days')
      AND store = 'Harbor Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-51 days'),
  a.id,
  'expense',
  'Cedar Bistro',
  'Dinner out',
  'Dining',
  NULL,
  -6400,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Dinner out'
      AND date = date('now', '-51 days')
      AND store = 'Cedar Bistro'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-39 days'),
  a.id,
  'expense',
  'Harbor Cafe',
  'Coffee and pastry',
  'Dining',
  NULL,
  -720,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Coffee and pastry'
      AND date = date('now', '-39 days')
      AND store = 'Harbor Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-24 days'),
  a.id,
  'expense',
  'Lakeside Diner',
  'Weekend brunch',
  'Dining',
  NULL,
  -4200,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekend brunch'
      AND date = date('now', '-24 days')
      AND store = 'Lakeside Diner'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-11 days'),
  a.id,
  'expense',
  'Harbor Cafe',
  'Afternoon coffee',
  'Dining',
  NULL,
  -580,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Afternoon coffee'
      AND date = date('now', '-11 days')
      AND store = 'Harbor Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-4 days'),
  a.id,
  'expense',
  'Cedar Bistro',
  'Shared dinner',
  'Dining',
  NULL,
  -7100,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Shared dinner'
      AND date = date('now', '-4 days')
      AND store = 'Cedar Bistro'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-88 days'),
  a.id,
  'expense',
  'City Transit',
  'Monthly pass',
  'Transport',
  NULL,
  -12000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly pass'
      AND date = date('now', '-88 days')
      AND store = 'City Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-58 days'),
  a.id,
  'expense',
  'City Transit',
  'Monthly pass',
  'Transport',
  NULL,
  -12000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly pass'
      AND date = date('now', '-58 days')
      AND store = 'City Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-27 days'),
  a.id,
  'expense',
  'City Transit',
  'Monthly pass',
  'Transport',
  NULL,
  -12000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly pass'
      AND date = date('now', '-27 days')
      AND store = 'City Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-86 days'),
  a.id,
  'expense',
  'Metro Utilities',
  'Electric and water',
  'Utilities',
  NULL,
  -15300,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Electric and water'
      AND date = date('now', '-86 days')
      AND store = 'Metro Utilities'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-55 days'),
  a.id,
  'expense',
  'Metro Utilities',
  'Electric and water',
  'Utilities',
  NULL,
  -15050,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Electric and water'
      AND date = date('now', '-55 days')
      AND store = 'Metro Utilities'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-25 days'),
  a.id,
  'expense',
  'Metro Utilities',
  'Electric and water',
  'Utilities',
  NULL,
  -15050,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Electric and water'
      AND date = date('now', '-25 days')
      AND store = 'Metro Utilities'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-80 days'),
  a.id,
  'expense',
  'Cloud Notes',
  'Notes subscription',
  'Subscriptions',
  NULL,
  -999,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Notes subscription'
      AND date = date('now', '-80 days')
      AND store = 'Cloud Notes'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-50 days'),
  a.id,
  'expense',
  'Cloud Notes',
  'Notes subscription',
  'Subscriptions',
  NULL,
  -999,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Notes subscription'
      AND date = date('now', '-50 days')
      AND store = 'Cloud Notes'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-19 days'),
  a.id,
  'expense',
  'Cloud Notes',
  'Notes subscription',
  'Subscriptions',
  NULL,
  -999,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Notes subscription'
      AND date = date('now', '-19 days')
      AND store = 'Cloud Notes'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-73 days'),
  a.id,
  'expense',
  'Cedar Pharmacy',
  'Household pharmacy',
  'Health',
  NULL,
  -2850,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Household pharmacy'
      AND date = date('now', '-73 days')
      AND store = 'Cedar Pharmacy'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-16 days'),
  a.id,
  'expense',
  'Cedar Pharmacy',
  'Vitamins',
  'Health',
  NULL,
  -1640,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Vitamins'
      AND date = date('now', '-16 days')
      AND store = 'Cedar Pharmacy'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-47 days'),
  a.id,
  'expense',
  'Northwind Books',
  'Paperback and notebook',
  'Shopping',
  NULL,
  -3200,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Paperback and notebook'
      AND date = date('now', '-47 days')
      AND store = 'Northwind Books'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-9 days'),
  a.id,
  'expense',
  'Northwind Books',
  'Children storybook',
  'Shopping',
  NULL,
  -1450,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Children storybook'
      AND date = date('now', '-9 days')
      AND store = 'Northwind Books'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-62 days'),
  a.id,
  'expense',
  'Example Fuel',
  'Full tank',
  'Transport',
  'Fuel',
  -5400,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Full tank'
      AND date = date('now', '-62 days')
      AND store = 'Example Fuel'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-33 days'),
  a.id,
  'expense',
  'Example Fuel',
  'Full tank',
  'Transport',
  'Fuel',
  -5120,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Full tank'
      AND date = date('now', '-33 days')
      AND store = 'Example Fuel'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-6 days'),
  a.id,
  'refund',
  'Neighborhood Market',
  'Returned produce',
  'Food',
  'Groceries',
  1200,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Returned produce'
      AND date = date('now', '-6 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-13 days'),
  a.id,
  'expense',
  'Neighborhood Market',
  'Market basket',
  'Food',
  'Groceries',
  -6340,
  'manual',
  'Sample fiscal receipt for the demo household',
  'https://example.com/receipts/demo-fiscal-2401',
  'DEMO-FISCAL-2401'
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Market basket'
      AND date = date('now', '-13 days')
      AND store = 'Neighborhood Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-44 days'),
  a.id,
  'expense',
  'Harbor Cafe',
  'Card coffee',
  'Dining',
  NULL,
  -610,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Card' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Card coffee'
      AND date = date('now', '-44 days')
      AND store = 'Harbor Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-22 days'),
  a.id,
  'expense',
  'Northwind Books',
  'Card bookstore',
  'Shopping',
  NULL,
  -2800,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Card' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Card bookstore'
      AND date = date('now', '-22 days')
      AND store = 'Northwind Books'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-10 days'),
  a.id,
  'expense',
  'Cedar Pharmacy',
  'Card pharmacy',
  'Health',
  NULL,
  -2190,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Everyday Card' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Card pharmacy'
      AND date = date('now', '-10 days')
      AND store = 'Cedar Pharmacy'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-71 days'),
  a.id,
  'income',
  'Example Bank',
  'Savings interest',
  'Income',
  'Interest',
  1850,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Emergency Savings' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Savings interest'
      AND date = date('now', '-71 days')
      AND store = 'Example Bank'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-41 days'),
  a.id,
  'expense',
  'Harbor Inn',
  'Two-night stay',
  'Travel',
  'Lodging',
  -12800,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Travel Cash' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Two-night stay'
      AND date = date('now', '-41 days')
      AND store = 'Harbor Inn'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-40 days'),
  a.id,
  'expense',
  'Rhine Bakery',
  'Breakfast pastry',
  'Dining',
  NULL,
  -640,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Travel Cash' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Breakfast pastry'
      AND date = date('now', '-40 days')
      AND store = 'Rhine Bakery'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-39 days'),
  a.id,
  'expense',
  'City Transit',
  'Day ticket',
  'Transport',
  NULL,
  -820,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Travel Cash' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Day ticket'
      AND date = date('now', '-39 days')
      AND store = 'City Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-38 days'),
  a.id,
  'expense',
  'Corner Market',
  'Travel snacks',
  'Food',
  NULL,
  -1850,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Travel Cash' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Travel snacks'
      AND date = date('now', '-38 days')
      AND store = 'Corner Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-65 days'),
  a.id,
  'income',
  'Rhine Design Studio',
  'Contract payment',
  'Income',
  'Freelance',
  180000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Rhine Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Contract payment'
      AND date = date('now', '-65 days')
      AND store = 'Rhine Design Studio'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-36 days'),
  a.id,
  'expense',
  'Rhine Bakery',
  'Weekly bread',
  'Food',
  'Groceries',
  -1850,
  'manual',
  'Sample fiscal receipt for a euro account',
  'https://example.com/receipts/demo-fiscal-2402',
  'DEMO-FISCAL-2402'
FROM accounts a
WHERE a.name = 'Rhine Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly bread'
      AND date = date('now', '-36 days')
      AND store = 'Rhine Bakery'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-18 days'),
  a.id,
  'expense',
  'Rhine Market',
  'Neighborhood groceries',
  'Food',
  'Groceries',
  -6240,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Rhine Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Neighborhood groceries'
      AND date = date('now', '-18 days')
      AND store = 'Rhine Market'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-8 days'),
  a.id,
  'expense',
  'Rhine Transit',
  'Monthly pass',
  'Transport',
  NULL,
  -8900,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Rhine Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly pass'
      AND date = date('now', '-8 days')
      AND store = 'Rhine Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-52 days'),
  a.id,
  'income',
  'Thames Studio',
  'Side project payment',
  'Income',
  'Freelance',
  85000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Sterling Current' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Side project payment'
      AND date = date('now', '-52 days')
      AND store = 'Thames Studio'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-29 days'),
  a.id,
  'expense',
  'Thames Grocer',
  'Weekly groceries',
  'Food',
  'Groceries',
  -5400,
  'manual',
  'Sample fiscal receipt for a sterling account',
  'https://example.com/receipts/demo-fiscal-2403',
  'DEMO-FISCAL-2403'
FROM accounts a
WHERE a.name = 'Sterling Current' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-29 days')
      AND store = 'Thames Grocer'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-17 days'),
  a.id,
  'expense',
  'Thames Transit',
  'Oyster top-up',
  'Transport',
  NULL,
  -3000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Sterling Current' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Oyster top-up'
      AND date = date('now', '-17 days')
      AND store = 'Thames Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-5 days'),
  a.id,
  'expense',
  'Thames Cafe',
  'Tea and sandwich',
  'Dining',
  NULL,
  -1250,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Sterling Current' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Tea and sandwich'
      AND date = date('now', '-5 days')
      AND store = 'Thames Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-46 days'),
  a.id,
  'income',
  'Maple Studio',
  'Contract payment',
  'Income',
  'Freelance',
  210000,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Maple Everyday' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Contract payment'
      AND date = date('now', '-46 days')
      AND store = 'Maple Studio'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-23 days'),
  a.id,
  'expense',
  'Maple Grocer',
  'Weekly groceries',
  'Food',
  'Groceries',
  -9800,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Maple Everyday' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Weekly groceries'
      AND date = date('now', '-23 days')
      AND store = 'Maple Grocer'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-12 days'),
  a.id,
  'expense',
  'Maple Transit',
  'Monthly pass',
  'Transport',
  NULL,
  -12800,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Maple Everyday' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Monthly pass'
      AND date = date('now', '-12 days')
      AND store = 'Maple Transit'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-3 days'),
  a.id,
  'expense',
  'Maple Cafe',
  'Coffee',
  'Dining',
  NULL,
  -650,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Maple Everyday' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Coffee'
      AND date = date('now', '-3 days')
      AND store = 'Maple Cafe'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, comment, receipt_url, fiscal_receipt_id
)
SELECT
  date('now', '-61 days'),
  a.id,
  'income',
  'Maple Credit Union',
  'Savings interest',
  'Income',
  'Interest',
  2400,
  'manual',
  NULL,
  NULL,
  NULL
FROM accounts a
WHERE a.name = 'Maple Savings' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Savings interest'
      AND date = date('now', '-61 days')
      AND store = 'Maple Credit Union'
  );

INSERT INTO planned_items (
  date, title, amount_minor, currency, account_id, category, done
)
SELECT
  date('now', '+21 days'),
  'Weekend rail tickets',
  -8900,
  'USD',
  a.id,
  'Travel',
  0
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM planned_items
    WHERE title = 'Weekend rail tickets' AND account_id = a.id
  );

INSERT INTO planned_items (
  date, title, amount_minor, currency, account_id, category, done
)
SELECT
  date('now', '+45 days'),
  'Replacement laptop',
  -120000,
  'USD',
  a.id,
  'Shopping',
  0
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM planned_items
    WHERE title = 'Replacement laptop' AND account_id = a.id
  );

INSERT INTO planned_items (
  date, title, amount_minor, currency, account_id, category, done
)
SELECT
  date('now', '+18 days'),
  'Rhine apartment insurance',
  -14500,
  'EUR',
  a.id,
  'Insurance',
  0
FROM accounts a
WHERE a.name = 'Rhine Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM planned_items
    WHERE title = 'Rhine apartment insurance' AND account_id = a.id
  );

INSERT INTO planned_items (
  date, title, amount_minor, currency, account_id, category, done
)
SELECT
  date('now', '-12 days'),
  'Hallway lamp',
  -4500,
  'USD',
  a.id,
  'Home',
  1
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM planned_items
    WHERE title = 'Hallway lamp' AND account_id = a.id
  );

INSERT INTO planned_items (
  date, title, amount_minor, currency, account_id, category, done
)
SELECT
  date('now', '+6 days'),
  'City museum tickets',
  -28000,
  'EUR',
  a.id,
  'Travel',
  0
FROM accounts a
WHERE a.name = 'Travel Cash' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM planned_items
    WHERE title = 'City museum tickets' AND account_id = a.id
  );

INSERT INTO planned_items (
  date, title, amount_minor, currency, account_id, category, done
)
SELECT
  date('now', '+48 days'),
  'Winter boiler service',
  -180000,
  'GBP',
  a.id,
  'Home',
  0
FROM accounts a
WHERE a.name = 'Sterling Current' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM planned_items
    WHERE title = 'Winter boiler service' AND account_id = a.id
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, planned_item_id
)
SELECT
  p.date,
  p.account_id,
  'expense',
  'Harbor Home',
  'Hallway lamp',
  'Home',
  NULL,
  p.amount_minor,
  'planned',
  p.id
FROM planned_items p
JOIN accounts a ON a.id = p.account_id
WHERE p.title = 'Hallway lamp'
  AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations WHERE planned_item_id = p.id
  );

INSERT INTO recurring_items (
  title, amount_minor, currency, account_id, category, frequency, interval_count,
  day_of_month, month_of_year, next_due_date, active
)
SELECT
  'Monthly salary',
  320000,
  'USD',
  a.id,
  'Income',
  'monthly',
  1,
  1,
  NULL,
  date('now', 'start of month', '+1 month'),
  1
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM recurring_items
    WHERE title = 'Monthly salary' AND account_id = a.id
  );

INSERT INTO recurring_items (
  title, amount_minor, currency, account_id, category, frequency, interval_count,
  day_of_month, month_of_year, next_due_date, active
)
SELECT
  'City rent',
  -180000,
  'USD',
  a.id,
  'Housing',
  'monthly',
  1,
  1,
  NULL,
  date('now', 'start of month', '+1 month'),
  1
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM recurring_items
    WHERE title = 'City rent' AND account_id = a.id
  );

INSERT INTO recurring_items (
  title, amount_minor, currency, account_id, category, frequency, interval_count,
  day_of_month, month_of_year, next_due_date, active
)
SELECT
  'Streamline Internet',
  -6500,
  'USD',
  a.id,
  'Utilities',
  'monthly',
  1,
  CAST(strftime('%d', date('now', '+12 days')) AS INTEGER),
  NULL,
  date('now', '+12 days'),
  1
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM recurring_items
    WHERE title = 'Streamline Internet' AND account_id = a.id
  );

INSERT INTO recurring_items (
  title, amount_minor, currency, account_id, category, frequency, interval_count,
  day_of_month, month_of_year, next_due_date, active
)
SELECT
  'Weekly produce box',
  -2800,
  'USD',
  a.id,
  'Food',
  'weekly',
  1,
  NULL,
  NULL,
  date('now', '+4 days'),
  1
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM recurring_items
    WHERE title = 'Weekly produce box' AND account_id = a.id
  );

INSERT INTO recurring_items (
  title, amount_minor, currency, account_id, category, frequency, interval_count,
  day_of_month, month_of_year, next_due_date, active
)
SELECT
  'Annual travel insurance',
  -18600,
  'USD',
  a.id,
  'Insurance',
  'yearly',
  1,
  CAST(strftime('%d', date('now', '+90 days')) AS INTEGER),
  CAST(strftime('%m', date('now', '+90 days')) AS INTEGER),
  date('now', '+90 days'),
  1
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM recurring_items
    WHERE title = 'Annual travel insurance' AND account_id = a.id
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, recurring_item_id
)
SELECT
  date('now', '-19 days'),
  r.account_id,
  'expense',
  'Streamline Internet',
  'Monthly internet',
  'Utilities',
  NULL,
  -6500,
  'recurring',
  r.id
FROM recurring_items r
JOIN accounts a ON a.id = r.account_id
WHERE r.title = 'Streamline Internet'
  AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE recurring_item_id = r.id AND date = date('now', '-19 days')
  );

INSERT INTO transfers
SELECT NULL
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Transfer to emergency savings' AND kind = 'transfer_out'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, transfer_id
)
SELECT
  date('now', '-20 days'),
  a.id,
  'transfer_out',
  NULL,
  'Transfer to emergency savings',
  'Transfers',
  NULL,
  -40000,
  'manual',
  (SELECT MAX(id) FROM transfers)
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Transfer to emergency savings' AND kind = 'transfer_out'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, transfer_id
)
SELECT
  date('now', '-20 days'),
  a.id,
  'transfer_in',
  NULL,
  'Transfer to emergency savings (in)',
  'Transfers',
  NULL,
  40000,
  'manual',
  (SELECT MAX(id) FROM transfers)
FROM accounts a
WHERE a.name = 'Emergency Savings' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Transfer to emergency savings (in)' AND kind = 'transfer_in'
  );

INSERT INTO transfers
SELECT NULL
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Travel cash top-up' AND kind = 'transfer_out'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, transfer_id
)
SELECT
  date('now', '-43 days'),
  a.id,
  'transfer_out',
  NULL,
  'Travel cash top-up',
  'Transfers',
  NULL,
  -20000,
  'manual',
  (SELECT MAX(id) FROM transfers)
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Travel cash top-up' AND kind = 'transfer_out'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, transfer_id
)
SELECT
  date('now', '-43 days'),
  a.id,
  'transfer_in',
  NULL,
  'Travel cash top-up (in)',
  'Transfers',
  NULL,
  18500,
  'manual',
  (SELECT MAX(id) FROM transfers)
FROM accounts a
WHERE a.name = 'Travel Cash' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Travel cash top-up (in)' AND kind = 'transfer_in'
  );

INSERT INTO transfers
SELECT NULL
WHERE EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Card payment' AND kind = 'transfer_out'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, transfer_id
)
SELECT
  date('now', '-8 days'),
  a.id,
  'transfer_out',
  NULL,
  'Card payment',
  'Transfers',
  NULL,
  -15000,
  'manual',
  (SELECT MAX(id) FROM transfers)
FROM accounts a
WHERE a.name = 'Everyday Checking' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Card payment' AND kind = 'transfer_out'
  );

INSERT INTO operations (
  date, account_id, kind, store, item, category, subcategory, amount_minor,
  source, transfer_id
)
SELECT
  date('now', '-8 days'),
  a.id,
  'transfer_in',
  NULL,
  'Card payment (in)',
  'Transfers',
  NULL,
  15000,
  'manual',
  (SELECT MAX(id) FROM transfers)
FROM accounts a
WHERE a.name = 'Everyday Card' AND a.owner = 'Household'
  AND EXISTS (SELECT 1 FROM settings WHERE key = 'setup_demo_seed' AND value = '1')
  AND NOT EXISTS (
    SELECT 1 FROM operations
    WHERE item = 'Card payment (in)' AND kind = 'transfer_in'
  );
